export const ENV_MONITOR_TEXT = Object.freeze({
  DEFAULT_STATION_NAME: "储能站点",
  DEFAULT_CONTAINER_PREFIX: "储能柜_",
  LOADING: "加载中...",
  EMPTY: "暂无拓扑数据",
  FETCH_ERROR: "环境监控数据加载失败，请稍后重试",
  RETRY: "重试",
  NO_DATA: "暂无数据",
  FIRE_ALARM_LIST: "告警列表",
  FIRE_DEFAULT_ALARM: "消防告警",
  ENV_TITLE: "环境监控",
  LIQUID_TITLE: "液冷系统",
  DEHUMIDIFIER_TITLE: "除湿机",
  FIRE_TITLE: "消防系统",
  LIQUID_MODE: "工作模式",
  LIQUID_TEMP: "环境温度",
  DEHUMIDIFIER_HUMIDITY: "当前湿度",
  DEHUMIDIFIER_TEMP: "当前温度",
  DEHUMIDIFIER_STATUS: "工作状态",
});

export const ENV_MONITOR_DEV_MOCK_FLAG = "REACT_APP_ENV_MONITOR_USE_MOCK";

export const ENV_MODULE_TYPE = Object.freeze({
  LIQUID_COOLING: "LIQUID_COOLING",
  DEHUMIDIFIER: "DEHUMIDIFIER",
  FIRE: "FIRE",
});

export const ENV_MODULE_TYPE_ALIASES = Object.freeze({
  [ENV_MODULE_TYPE.LIQUID_COOLING]: ["LIQUID_COOLING", "LIQUIDCOOLING", "LIQUID", "COOLING"],
  [ENV_MODULE_TYPE.DEHUMIDIFIER]: ["DEHUMIDIFIER", "DEHUMIDIFY", "DEHUM"],
  [ENV_MODULE_TYPE.FIRE]: ["FIRE", "FIRE_SYSTEM", "FIREFIGHTING", "FIRE_FIGHTING"],
});

export const ENV_METRIC_CODE = Object.freeze({
  MODE: "MODE",
  TEMPERATURE: "TEMPERATURE",
  HUMIDITY: "HUMIDITY",
  STATUS: "STATUS",
});

export const ENV_METRIC_CODE_ALIASES = Object.freeze({
  [ENV_METRIC_CODE.MODE]: ["MODE", "WORK_MODE", "RUN_MODE", "OPERATION_MODE"],
  [ENV_METRIC_CODE.TEMPERATURE]: ["TEMPERATURE", "TEMP", "AMBIENT_TEMPERATURE"],
  [ENV_METRIC_CODE.HUMIDITY]: ["HUMIDITY", "HUMI", "RELATIVE_HUMIDITY"],
  [ENV_METRIC_CODE.STATUS]: ["STATUS", "WORK_STATUS", "RUN_STATUS", "STATE"],
});

export const ENV_FIRE_DISPLAY_TYPE = Object.freeze({
  LIST: "LIST",
  STATUS: "STATUS",
  EMPTY: "EMPTY",
});
