export default {
    primaryColor: ['#237AE4'],
    errorColor: ['#ff4d4f'],
    warningColor: ['#faad14'],
    successColor: ['#52c41a'],
    infoColor: ['#1890ff'],
    menusbgcolor: ["#003366"],
    menusfontcolor: ["#b2c1d1"],
    menusactive: ['#1c62b6'],
    menusborder: ['#00ff66'],
    menusactivefontcolor: ['#ffffff'],
    menusbgcolorR: ['#135abd'],
    menusbgcolorRA: ['#3988e7'],
    menusbgcolorRfont: ['#ffffff'],
    menusbgcolorRborder: ['#ffffff'],
    runasiderstart:["#0b41c7"],
    runasiderend:["#7662ff"],
    desasiderstart:["#003399"],
    desasiderend:["#003333"],
    asiderfontcolor: ["#ffffff"],
    asiderfontcolorA: ["#33ff00"],
    asiderbgcolorA:["#3333cc"],
}