export default {
    primaryColor: ['#237AE4'],
    errorColor: ['#ff4d4f'],
    warningColor: ['#faad14'],
    successColor: ['#52c41a'],
    infoColor: ['#1890ff'],
    menusbgcolor: ["#003366"],
    menusfontcolor: ["#b2c1d1"],
    menusactive: ['#1c62b6'],
    menusborder: ['#00ff66'],
    menusactivefontcolor: ['#ffffff'],
    menusbgcolorR: ['#135abd'],
    menusbgcolorRA: ['#3988e7'],
    menusbgcolorRfont: ['#ffffff'],
    menusbgcolorRborder: ['#ffffff'],
    runasiderstart:["#0b41c7"],
    runasiderend:["#7662ff"],
    desasiderstart:["#003399"],
    desasiderend:["#003333"],
    asiderfontcolor: ["#ffffff"],
    asiderfontcolorA: ["#33ff00"],
    asiderbgcolorA:["#3333cc"],
    previewrbgcolor:["#135abd"],
    gatewayheardcolor:["#003366"],
    gatewayheardcolorend:["#003366"],
    gatewaybgcolor:["#135abd"],
    deviceheardcolor:["#003366"],
    devicebgcolor:["#135abd"],
    normalColor: ["#009966"],
    warningColorstate: ["#ff4d4f"],
    offlineColor: ["#666666"],
    fntnormalColor: ["#ffffff"],
    fntwarningColorstate: ["#ffffff"],
    fntofflineColor: ["#ffffff"],
    fieldname: ["#ffffff"],
    fieldvalue: ["#1E50E6"],
 //   itembg:["#000033"],
    disfieldname: ["#ffffff"],
    disfieldvalue: ["#00ff00"],
    dislistbg:["#334461e"],
    disitemhover: ["#6633ff"],
    carnstrokecolor: ["#ffff99"],
    carntrailcolor: ["#6633cc"],
    bgcolorfont: ["#ffffff"],
    startColor:["#ffffff"],
    endColor:["#1c62b6"],
    logBgColor:["1c62b6"],
    cardHeadBg: ["#dee7f2"],
    cardHeadlColor: ["#303133"],
    imgbgcolor:["#4A9AF0"],
}
export const initithemeColor = {  // 可配置对象，不只是颜色属性。名字为保证稳定性不改
    id:0, 
    name:'',
    primaryColor: '#237AE4',
    islight: false, // 150
    errorColor: '#ff4d4f',
    warningColor: '#faad14',
    successColor: '#52c41a',
    infoColor: '#1890ff',
    menusbgcolor: '#003366',
    menusbgcolorR: '#135abd',
    menusbgcolorRA: '#3988e7',
    menusbgcolorRfont: '#ffffff',
    menusbgcolorRborder: '#ffffff',
    menusfontcolor: "#b2c1d1",
    menusactive: '#1c62b6',
    menusborder: '#00ff66',
    menusactivefontcolor: '#ffffff',
    runasiderstart:"#0b41c7",
    runasiderend:"#7662ff",
    desasiderstart:"#003399",
    desasiderend:"#003333",
    asiderfontcolor: "#ffffff",
    asiderfontcolorA: "#33ff00",
    asiderbgcolorA:"#3333cc",
    previewrbgcolor:"#135abd" , // 项目概览背景色
    gatewayheardcolor:"#003366" , // 网关详情页起始色
    gatewayheardcolorend:"#003366" , // 网关详情页结束色
    gatewaybgcolor:"#135abd", // 网关详情页背景色
    deviceheardcolor:"#003366" , // 设备详情页标题色
    devicebgcolor:"#135abd", // 设备详情页背景色
    normalColor: "#009966",
    warningColorstate: "#ff4d4f",
    offlineColor: "#666666",
    fntnormalColor: "#ffffff",
    fntwarningColorstate: "#ffffff",
    fntofflineColor: "#ffffff",
    echartfirstcolor:"#237AE4",
    fieldname: "#ffffff",
    fieldvalue: "#1E50E6",
  //  itembg:"#000033",
    primaryderived:'#4a9af0',
    disfieldname: "#ffffff",
    disfieldvalue: "#00ff00",
    dislistbg:"#334461",
    disitemhover: "#6633ff",
    carnstrokecolor: "#ffff99",
    carntrailcolor: "#6633cc",
    darkcolor: 'rgba(0, 0, 0, 0.45)',
    lingtcolor:"#ffffff",
    bgcolorfont: "#ffffff",
    startColor:"#ffffff",
    endColor:"#1c62b6",
    logBgColor:"#1c62b6",
    cardHeadBg: "#dee7f2",
    cardHeadlColor: "#303133",
    imgbgcolor:"#4A9AF0",
  }
  export const themeOption = {
    opacity:0.2,
    startOpacity:0,
    endOpacity:0.2,
    cardHeadHeight:40,
    cardRadius:8,
 }