export default {
    primaryColor: ['#237AE4'],
    errorColor: ['#ff4d4f'],
    warningColor: ['#faad14'],
    successColor: ['#52c41a'],
    infoColor: ['#1890ff'],
    menusbgcolor: ["#036"],
    menusfontcolor: ["#b2c1d1"],
    menusactive: ['#1c62b6'],
    menusborder: ['#0f6'],
    menusactivefontcolor: ['#fff'],
    menusbgcolorR: ['#135abd'],
    menusbgcolorRA: ['#3988e7'],
    menusbgcolorRfont: ['#fff'],
    menusbgcolorRborder: ['#fff'],
    runasiderstart:["#0b41c7"],
    runasiderend:["#7662ff"],
    desasiderstart:["#039"],
    desasiderend:["#033"],
    asiderfontcolor: ["#fff"],
    asiderfontcolorA: ["#3f0"],
}